### ISSUE TITLE
can't unlock bootloader on a Nokia Lumia 635

### ISSUE THREAD

**Issue by breadbrowser** [ReneLergner/WPinternals#36]

**Comment by JustNewHere** [comment]
Follow this guide: https://mega.nz/folder/82YgQabJ#in_YEkxi0vCj_DmBfms5ig/file/B25WHBQY and use this donor FFU: https://mega.nz/folder/82YgQabJ#in_YEkxi0vCj_DmBfms5ig/file/YjxG1LaR

**Comment by breadbrowser** [comment]
still didn't work

**Comment by gus33000** [comment]
Please refile this issue and attach the extremely important WPinternals.log file and do not clear our the issue template (please fill it properly). This kind of bug report is otherwise not actionable for us if you refuse to fill in the bug reporting template and provide no log file. Thank you.

---

Bug reporting template:

![image](https://github.com/user-attachments/assets/a3ac01dc-b49b-40a5-89bb-a8b85d784536)

__Please do not ignore it!__
