### ISSUE TITLE
Lumia 535 stuck in Flash Mode

### ISSUE THREAD

**Issue by raidrob** [ReneLergner/WPinternals#38]
### Description

I tried to unlock the bootloader of a Lumia 535 to get the device into mass storage mode. But something went wrong (see log). Now the device is in flash mode (red screen) and iam not able to boot it into normal mode again.
What can i do to fix it without wipe userdata?

### Expected behavior

Unlock bootloader to enter mass storage mode

### WPinternals Version

2.9.2 and 2.8

### Windows Version

Windows 10 Pro 21H2

### Phone model

Lumia 535 

### Relevant Assets

[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/7992922/WPInternals.log)

**Comment by gus33000** [comment]
There is no way to fix a device that cannot be unlocked by WPinternals due to the exploit being used not working on the device other than completely reflashing it. (cf. instructions/text/guidance on WPinternals. The Lumia 535 is not supported by WPinternals currently, there is a few issues already about this and we removed it from the list with https://github.com/ReneLergner/WPinternals/commit/5eb523530cfddda3e0165a528d7e6593069ec856

Simply reflash your device completely using Windows Device Recovery Tool. No other way.
