### ISSUE TITLE
Failed to write to pipe: 4E4F4B53

### ISSUE THREAD

**Issue by Daviidkoo4074** [ReneLergner/WPinternals#45]
Im still getting this error while trying to unlock bootlader on my Lumia 650. I tried to remove SD-Card but same problem.

**Comment by gus33000** [comment]
Please refile this issue and attach the extremely important WPinternals.log file and do not clear our the issue template (please fill it properly). This kind of bug report is otherwise not actionable for us if you refuse to fill in the bug reporting template and provide no log file. Thank you.

---

Bug reporting template:

![image](https://github.com/user-attachments/assets/a3ac01dc-b49b-40a5-89bb-a8b85d784536)

__Please do not ignore it!__
