### ISSUE TITLE
Error: Failed to read sector. Exception: 0x00000002

### ISSUE THREAD

**Issue by Hemp007** [ReneLergner/WPinternals#5]
Не разблокируется загрузчик. В чем может быть проблема?
![1234](https://user-images.githubusercontent.com/50801887/57983876-a5f1ca80-7a80-11e9-9751-0aefbaf850be.jpg)
![12345](https://user-images.githubusercontent.com/50801887/57983877-abe7ab80-7a80-11e9-8e6f-f8784b9326d1.jpg)

**Comment by gus33000** [comment]
Can you please provide more information in english if possible?

**Comment by gus33000** [comment]
Hi,

We didn't hear back from you in ages, are you still having this issue? We might have to close this issue if we don't hear back from you in a few days...

(New version: https://github.com/ReneLergner/WPinternals/releases/tag/2.9)

**Comment by garhold** [comment]
The same issue here with Nokia Lumia RM-1118 in WPinternals 2.9.2 win-x64.

It happens when rebooting the phone in Mass Storage mode.

Windows offers to format the disk which of course I do not.

In device manager 40 partitions appear related to the phone.

Event ID 11 is logged in Windows 'Driver detected a controller error'.

Is there a work around to this problem ?

![0x00000002exception](https://user-images.githubusercontent.com/106425903/170817058-eb204669-9db6-4100-b9d2-f9fbf8a2121f.jpg)

![40partitions](https://user-images.githubusercontent.com/106425903/170817158-db61109f-8871-452c-b111-7152dfb63c57.jpg)
