### ISSUE TITLE
WP internals hanging and freezing when attempting to unlock device

### ISSUE THREAD

**Issue by AttackVector** [ReneLergner/WPinternals#67]
I have tried dozens of cables and the program hangs when i try unlocking the device or do any action. I really want to unlock my WP8.1 Phone. It is a lumia 925 att

**Comment by JoveyMcJupi** [comment]
Same issue here. Can't unlock the device, but mine is a Lumia 640 LTE. Running Canary build of Windows 11, might have to do something with it. Will try Windows 7, or 10.

**Comment by MackaG** [comment]
did you solve the issue?

**Comment by gus33000** [comment]
Please refile this issue and attach the extremely important WPinternals.log file and do not clear our the issue template (please fill it properly). This kind of bug report is otherwise not actionable for us if you refuse to fill in the bug reporting template and provide no log file. Thank you.

---

Bug reporting template:

![image](https://github.com/user-attachments/assets/a3ac01dc-b49b-40a5-89bb-a8b85d784536)

__Please do not ignore it!__
