### ISSUE TITLE
Can't open WPI

### ISSUE THREAD

**Issue by haigamingP** [ReneLergner/WPinternals#85]
![image](https://github.com/user-attachments/assets/b45e2cf6-217d-4bb5-af40-1ebcbbf4d537)

**Comment by jack-obrien** [comment]
Looks like this would explain it: "This release being a preview build comes with caveats, known issues, and will expire on December 21, 2024."

From the release notes back in 2021: https://github.com/ReneLergner/WPinternals/releases/tag/3.0-preview4

**Comment by gus33000** [comment]
Prerelease versions are intended for evaluation purposes only and can have rough edges and be highly unstable to the point of breaking your device. This behavior is intended. If you care about your device please use the latest stable version; not preview. Otherwise; you can roll your date back at your own risk. This works as intended either way.
